

#????
server:
  port: 10006

spring:
  application:
    name: cloud-publicopinionmanage-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eqe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: 'root'
    password: '000000'


eureka:
  client:
    #??????????eurekaServer
    register-with-eureka: true
    #???eurekaServer?????????????true,??????????????true????ribbon??????
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka/
  #      http://eureka7002.com:7002/eureka/
  #      defaultZone: http://localhost:7001/eureka
  #  http://114.116.249.36:7001/eureka/
  instance:
    prefer-ip-address: true